# Generated by Django 4.1.2 on 2022-12-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="fechaInicio",
            field=models.DateField(default="2021-01-01"),
        ),
    ]
